spring.application.name=media-service

server.servlet.context-path=/api/media

spring.profiles.active=local

server.port=9090

eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true
eureka.instance.prefer-ip-address=true

logging.level.org.springframework.web.client.RestTemplate=WARN
logging.level.com.netflix.eureka=WARN
logging.level.com.netflix.discovery=WARN
logging.level.org.springframework.web.HttpLogging=WARN


# application.properties
spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=100MB